name: Maintenance

on:
  workflow_dispatch:

# For good reasons, GitHub Actions people made the decision to add the
# container: functionality. For some other reason, when running inside a
# container:, they made an insane, completely batshit crazy decision to set
# $HOME to something other than /root. This breaks a bunch of things, which is
# why all the insanity is there below.
#
# makepkg people are similarly insane, which is why they hard-forbid running
# makepkg as root, because they're crazy. This is cause for the other stupid
# workarounds below.

jobs:
  maintenance:
    name: Maintenance
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
      # This step must be done before actions/checkout. From the latter's
      # output:
      #
      #     To create a local Git repository instead, add Git 2.18 or higher to the PATH
      #
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm git openssh
      - name: Checkout
        uses: actions/checkout@v6
      - name: Add builder user
        run: |
          useradd -m -s /bin/bash builder
          chown -R builder:builder -- "$GITHUB_WORKSPACE"
      - name: Configure git
        run: |
          # See https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
          runuser -u builder -- git -C "$GITHUB_WORKSPACE" config user.name "github-actions[bot]"
          runuser -u builder -- git -C "$GITHUB_WORKSPACE" config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Run maintenance
        run: |
          runuser -u builder -- make -C "$GITHUB_WORKSPACE" maintenance
