name: Maintenance

on:
  schedule:
    # Weekly, at 02:30 UTC on Friday (somewhat randomly chosen).
    - cron: '30 02 * * 5'
  workflow_dispatch:

# For good reasons, GitHub Actions people made the decision to add the
# container: functionality. For some other reason, when running inside a
# container:, they made an insane, completely batshit crazy decision to set
# $HOME to something other than /root. This breaks a bunch of things, which is
# why all the insanity is there in aur:./Makefile
#
# makepkg people are similarly insane, which is why they hard-forbid running
# makepkg as root, because they're crazy. This is cause for the other stupid
# workarounds in aur:./Makefile

jobs:
  maintenance:
    name: Maintenance
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      env:
        SSH_KEY: |
          ${{ secrets.SSH_KEY }}
    steps:
      # This step must be done before actions/checkout. From the latter's
      # output:
      #
      #     To create a local Git repository instead, add Git 2.18 or higher to the PATH
      #
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm git openssh
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: aur
          # Without the token, GitHub returns 403.
          token: '${{ secrets.GH_TOKEN }}'
      - name: Run maintenance
        run: |
          make -C "$GITHUB_WORKSPACE" ci
